### GET buscar dados basicos de todos os cliente
GET http://localhost:3000/clientes


### GET todos os dados do cliente
GET http://localhost:3000/clientes/8

### POST Salvar cliente 1
POST http://localhost:3000/clientes
Content-Type: application/json

{
    "cliRazaoSocial": "Razao da empresa Teste",
    "cliNomeFantasia": "Empresa Teste",
    "cliTelefone": "(83) 98765-4321",
    "cliDocumento": "12.597.356/0001-33",
    "enderecos": [
        {
            "clieCep": "58071-400",
            "clieLogradouro": "RUA JOAO PE DE FEIJAO",
            "clieNumero": "1066/3",
            "clieBairro": "CENTRO",
            "clieCidade": "BARRA FUNDA",
            "clieUF": "SP"
        }
    ]
}


### DELETE deletar um Cliente pelo ID
DELETE http://localhost:3000/clientes/7

### POST Adicionar um endereço de um Cliente
POST http://localhost:3000/clientes/8/enderecos
Content-Type: application/json

{
    "clieCep": "58071-400",
    "clieLogradouro": "RUA JOAO PE DE FEIJAO",
    "clieNumero": "1066/3",
    "clieBairro": "RIO DO CENTRO",
    "clieCidade": "BARRA FUNDA",
    "clieUF": "PB",
    "clieReferencia": null
}

### PATCH Alterar um endereço de um Cliente
PATCH http://localhost:3000/clientes/8/enderecos/17
Content-Type: application/json

{
    "clieCep": "58993-000",
    "clieLogradouro": "RUA MARIA DA GUIA",
    "clieNumero": "1999",
    "clieBairro": "CENTRO",
    "clieCidade": "BARRA FUNDA",
    "clieUF": "SP",
    "clieReferencia": "PROXIMO AO MERCADO CENTRAL"
}

### POST Deletar um endereço de um Cliente
DELETE http://localhost:3000/clientes/8/enderecos/18
